<?php

class Tiny_Custom_Nav_Walker extends Walker_Nav_Menu {
	public function  start_lvl( &$output, $depth = 0, $args = null ) {
		$output             .= '<ul class="special-class">';
//		parent::start_lvl( $output, $depth, $args ); // TODO: Change the autogenerated stub
	}
}
